### ISSUE TITLE
ミリ秒の情報が落ちる

### ISSUE THREAD

**Issue by TeppeiKurahashi** [hecomi/uOSC#1]

**Comment by hecomi** [comment]
具体的なバグの症状・または再現方法を教えていただけないでしょうか。

**Comment by TeppeiKurahashi** [comment]
症状の報告遅くなってすみません。
TimeStamp.csの
`
public static Timestamp CreateFromDateTime(DateTime time)
    {
        var span = time - new DateTime(1900, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var sec = span.TotalSeconds;
        var msec = span.TotalMilliseconds - sec * 1000;
        var integerPart = (UInt32)sec;
        var decimalPart = (UInt32)msec;
        var timestamp = ((UInt64)integerPart << 32) | (UInt64)decimalPart;
        return new Timestamp(timestamp);
    }
`
この関数において、msecが常に0になります。おそらく、secの型がdoubleであり、ミリ秒の情報も小数点以下で含んでいることが原因と考えられます。TimeSpan.TotalSecondsの戻り値の型がIntではなくDoubleなので、varで指定したsecの型もDoubleになっています。
検討よろしくお願いします。

**Comment by hecomi** [comment]
詳細なご報告ありがとうございます。
修正して push しましたので、最新の master ブランチをご確認頂けますでしょうか。
期待する挙動でしたら .unitypackage 化してリリースいたします。
よろしくお願いいたします。

**Comment by TeppeiKurahashi** [comment]
確認遅くなりました。自分の用途では問題なく動作しました。修正ありがとうございました！

**Comment by hecomi** [comment]
作業遅れてしまい申し訳有りません。。
Releases にビルドを追加しましたので close します。
https://github.com/hecomi/uOSC/releases/tag/v0.0.2
